#!/bin/sh

if [ "$GNATS_HOME" = '' ] ;   then
	export GNATS_HOME=${PWD}
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GNATS_HOME/../GNATS_Server/dist

#sh $GNATS_HOME/utility/run_nodejs.sh &
#
#sleep 1

TARGET_PS=$(lsof -i tcp:2020 | awk 'NR!=1 {print $2}')

if [ "${TARGET_PS}" != '' ] ;   then
   set echo off
   
   kill -15 $TARGET_PS > /dev/null
   
   set echo on
fi

TARGET_PS=$(java -cp $GNATS_HOME/../GNATS_Server/dist/gnats-shared.jar:$GNATS_HOME/../GNATS_Server/dist/tools.jar ListJVM | grep 'GNATSStandaloneServer' | awk '{print $1}')

if [ "${TARGET_PS}" != '' ] ;   then
   set echo off

   kill -15 $TARGET_PS > /dev/null
   
   set echo on
fi

java -cp $GNATS_HOME/dist/gnats-standalone.jar:$GNATS_HOME/../GNATS_Server/dist/gnats-server.jar:$GNATS_HOME/../GNATS_Server/dist/gnats-shared.jar:$GNATS_HOME/../GNATS_Server/dist/commons-logging-1.2.jar:$GNATS_HOME/../GNATS_Server/dist/commons-compress-1.20.jar:$GNATS_HOME/../GNATS_Server/dist/tools.jar:$GNATS_HOME/../GNATS_Server/dist/spring_boot/* -Djava.library.path=$GNATS_HOME/dist:$GNATS_HOME/../GNATS_Server/dist -Xmx768m GNATSStandaloneServer
